    version: '3.8'

    services:
      front-end:
        build: ./client # Path to your Vite project directory
        ports:
          - "5171:80" # Map container port 80 to host port 80
        volumes:
          - ./client:/app # Mount for development, remove for production
        # depends_on:
        #   - note-stacks-back-end # Ensure Flask is running before Vite (if needed)
      back-end:
        build: ./server # Directory containing your Flask app and Dockerfile
        ports:
          - "5001:5001"
        environment:
          DATABASE_URI: mysql+mysqlconnector://user:password@mysql_db/mydatabase
        depends_on:
         - mysql_db
        volumes:
          - ../markdown:/app/markdown # Mount for markdown files
          - ../logs/note-stacks:/app/logs # Mount for logs
      
      mysql_db:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - "3306:3306" # Expose MySQL port
        volumes:
          - mysql_data:/var/lib/mysql

    volumes:
      mysql_data:

