# OS: Ubuntu 22.04
FROM debian:bookworm-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y npm \
    nodejs \
    python3 \ 
    python3-pip \
    python3-venv \
    nginx && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN node -v

# Set work directory
WORKDIR /app

# Copy code into the container
COPY . /app

#======================#
#   BACK-END SETTING   #
#======================#

# Move to the server directory
WORKDIR /app/server

# python environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install Flask and other dependencies
RUN pip install Flask
RUN pip install flask-mysql

# Expose the Flask port
EXPOSE 5001

# Use the Flask command to run the server   
RUN flask --app run server.py -p 5001

#=======================#
#   FRONT-END SETTING   #
#=======================#

# Move to the client directory
WORKDIR /app/client 

# Install npm
RUN npm install 

# Build Vite production
RUN npm run build

# NGX configuration
RUN cp /app/nginx/server.conf /etc/nginx/sites-available
RUN unlink /etc/nginx/sites-enabled/default
RUN ln -s /etc/nginx/sites-available/server.conf /etc/nginx/sites-enabled/
RUN nginx -t

# Copy the build output from the dist folder into the Nginx html directory
RUN cp -r dist/* /usr/share/nginx/html/

# Expose port 80 to allow access to the app
EXPOSE 5171:80

# Run Nginx in the foreground
ENTRYPOINT ["nginx", "-g", "daemon off;"] 






